title: Products
template: products/show
layout: layout
mount: fb0a9e91-b312-4af1-9836-7dccba0953fc
taxonomies:
  - categories
  - colors
revisions: false
route: '/products/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
